server:
  path: http://IP:{port}
  image:
    name: image
    path: '存放路徑 Ex: D:\course-management\UploadFile\${server.image.name}\'
  file:
    name: file
    path: '存放路徑 Ex: D:\course-management\UploadFile\${server.file.name}\'
logging:
  level:
    sqltiming: DEBUG
    resultsettable: DEBUG
course-management:
  database:
    url: jdbc:log4jdbc:mysql://{資料庫IP}:{port}/{資料庫名字}?serverTimezone=Asia/Taipei
    account: 帳號
    password: 密碼